version: '3.5'
services:
  test:
    image: golang:1.13
    command: sleep infinity
    volumes:
      - ./:/work
    working_dir: /work
    environment:
      SQS_ENDPOINT: http://localstack:4576
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secretsecret
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: sqs
    volumes:
      - localstack-data:/tmp/localstack

volumes:
  localstack-data:
    driver: local