version: '3.5'
services:
  test:
    image: golang:1.13
    command: sleep infinity
    volumes:
      - ./:/work
    working_dir: /work
    environment:
      SQS_ENDPOINT: http://localstack:4576
      SQS_QUEUE: my-queue
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secretsecret
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: sqs
    volumes:
      - localstack-data:/tmp/localstack

  sqs_init:
    image: maruware/awscli-wait-for-it
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secretsecret
    depends_on:
      - localstack
    entrypoint: >
      /wait-for-it.sh localstack:4576 -- 
        bash -c "
        aws --endpoint-url=http://localstack:4576 sqs create-queue --queue-name my-queue 
        "

volumes:
  localstack-data:
    driver: local